export const ROW_TITLES = {
  taskQueue: 'TASK QUEUE',
  microTaskQueue: 'MICRO TASK QUEUE',
  webApis: 'WEB API',
  callStack: 'CALL STACK',
  log: 'LOG'
};

export const VISUALISATION_EXAMPLES = {
  'promise-exec': {
    imageSrc: '../../assets/code-snippets/promises-exec.png',
    code: `
function getEmpDetails(emp) {
  return new Promise((resolve, reject) => {
    console.log('getEmpDetails Start');
    fetch('https://myorg.com/api/getEmpDetails/' + emp).then((data) => {
      console.log('getEmpDetails request done');
      resolve(data);
    });
    console.log('getEmpDetails EOF');
  });
}
function getBasicPay(emp) {
  return new Promise((resolve, reject) => {
    console.log('getBasicPay Start');
    fetch('https://myorg.com/api/getBasicPay/' + emp).then((data) => {
      console.log('getBasicPay request done');
      resolve(data);
    });
    console.log('getBasicPay EOF');
  });
}
function getHra(emp) {
  return new Promise((resolve, reject) => {
    console.log('getHra Start');
    fetch('https://myorg.com/api/getHra/' + emp).then((data) => {
      console.log('getHra request done');
      resolve(data);
    });
    console.log('getHra EOF');
  });
}
let salary;
getEmpDetails('emp').then((details) => {
  console.log('getEmpDetails Done', details);
  return Promise.all([getHra(details), getBasicPay(details)]);
}).then((result) => {
  console.log('Salary Done', result);
  salary = result[0] + result[1];
});
console.log('EOF');
`,
    codeLines: [
      '1. function getEmpDetails(emp) {',
      '2.   return new Promise((resolve, reject) => {',
      "3.     console.log('getEmpDetails Start');",
      "4.     fetch('https://myorg.com/api/getEmpDetails/' + emp).then((data) => {",
      "5.       console.log('getEmpDetails request done');",
      '6.       resolve(data);',
      '7.     });',
      "8.     console.log('getEmpDetails EOF');",
      '9.   });',
      '10. }',
      '11. function getBasicPay(emp) {',
      '12.   return new Promise((resolve, reject) => {',
      "13.     console.log('getBasicPay Start');",
      "14.     fetch('https://myorg.com/api/getBasicPay/' + emp).then((data) => {",
      "15.       console.log('getBasicPay request done');",
      '16.       resolve(data);',
      '17.     });',
      "18.     console.log('getBasicPay EOF');",
      '19.   });',
      '20. }',
      '21. function getHra(emp) {',
      '22.   return new Promise((resolve, reject) => {',
      "23.     console.log('getHra Start');",
      "24.     fetch('https://myorg.com/api/getHra/' + emp).then((data) => {",
      "25.       console.log('getHra request done');",
      '26.       resolve(data);',
      '27.     });',
      "28.     console.log('getHra EOF');",
      '29.   });',
      '30. }',
      '31. let salary;',
      "32. getEmpDetails('emp').then((details) => {",
      "33.   console.log('getEmpDetails Done', details);",
      '34.   return Promise.all([getHra(details), getBasicPay(details)]);',
      '35. }).then((result) => {',
      "36.   console.log('Salary Done', result);",
      '37.   salary = result[0] + result[1];',
      '38. });',
      "39. console.log('EOF');",
    ],
    examples: [
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [],
        log: [],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["getEmpDetails('emp')"],
        log: [],
        highlightKey: 32,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('getEmpDetails Start');",
          "getEmpDetails('emp')",
        ],
        log: [],
        highlightKey: 3,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["fetch('getEmpDetails')", "getEmpDetails('emp')"],
        log: ['getEmpDetails Start'],
        highlightKey: 4,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getEmpDetails')-Pending"],
        callStack: [
          "console.log('getEmpDetails EOF');",
          "getEmpDetails('emp')",
        ],
        log: ['getEmpDetails Start'],
        highlightKey: 8,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getEmpDetails')-Pending"],
        callStack: ["getEmpDetails('emp')"],
        log: ['getEmpDetails Start', 'getEmpDetails EOF'],
        highlightKey: 10,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getEmpDetails')-Resolved"],
        callStack: ["console.log('EOF');"],
        log: ['getEmpDetails Start', 'getEmpDetails EOF'],
        highlightKey: 39,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getEmpDetails')-Microtask"],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'getEmpDetails EOF', 'EOF'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["fetch('getEmpDetails')-Microtask"],
        log: ['getEmpDetails Start', 'getEmpDetails EOF', 'EOF'],
        highlightKey: 4,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('getEmpDetails request done');",
          "fetch('getEmpDetails')-Microtask",
        ],
        log: ['getEmpDetails Start', 'getEmpDetails EOF', 'EOF'],
        highlightKey: 5,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          'resolve(data);',
          "fetch('getEmpDetails')-Microtask",
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
        ],
        highlightKey: 6,
      },
      {
        taskQueue: [],
        microTaskQueue: ['getEmpDetails-MicroTask'],
        webApis: [],
        callStack: ["fetch('getEmpDetails')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
        ],
        highlightKey: 7,
      },
      {
        taskQueue: [],
        microTaskQueue: ['getEmpDetails-MicroTask'],
        webApis: [],
        callStack: [],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
        ],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
        ],
        highlightKey: 32,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('getEmpDetails Done', details);",
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
        ],
        highlightKey: 33,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['getHra(details)', 'getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
        ],
        highlightKey: 34,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('getHra Start');",
          'getHra(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
        ],
        highlightKey: 23,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "fetch('getHra')",
          'getHra(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
        ],
        highlightKey: 24,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getHra')-Pending"],
        callStack: [
          "console.log('getHra EOF');",
          'getHra(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
        ],
        highlightKey: 28,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getHra')-Resolved"],
        callStack: ['getHra(details)', 'getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
        ],
        highlightKey: 30,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getHra')-Microtask"],
        webApis: [],
        callStack: ['getBasicPay(details)', 'getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
        ],
        highlightKey: 34,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getHra')-Microtask"],
        webApis: [],
        callStack: [
          "console.log('getBasicPay Start');",
          'getBasicPay(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
        ],
        highlightKey: 13,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getHra')-Microtask"],
        webApis: [],
        callStack: [
          "fetch('getBasicPay')",
          'getBasicPay(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
        ],
        highlightKey: 14,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getHra')-Microtask"],
        webApis: ["fetch('getBasicPay')-Pending"],
        callStack: [
          "console.log('getHra EOF')",
          'getBasicPay(details)',
          'getEmpDetails-MicroTask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
        ],
        highlightKey: 18,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getHra')-Microtask"],
        webApis: ["fetch('getBasicPay')-Resolved"],
        callStack: ['getBasicPay(details)', 'getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
        ],
        highlightKey: 20,
      },
      {
        taskQueue: [],
        microTaskQueue: [
          "fetch('getHra')-Microtask",
          "fetch('getBasicPay')-Microtask",
        ],
        webApis: [],
        callStack: ['getEmpDetails-MicroTask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
        ],
        highlightKey: 35,
      },
      {
        taskQueue: [],
        microTaskQueue: [
          "fetch('getHra')-Microtask",
          "fetch('getBasicPay')-Microtask",
        ],
        webApis: [],
        callStack: [],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
        ],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getBasicPay')-Microtask"],
        webApis: [],
        callStack: ["fetch('getHra')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
        ],
        highlightKey: 24,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getBasicPay')-Microtask"],
        webApis: [],
        callStack: [
          "console.log('getHra request done')",
          "fetch('getHra')-Microtask",
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
        ],
        highlightKey: 25,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getBasicPay')-Microtask"],
        webApis: [],
        callStack: ['resolve(data)', "fetch('getHra')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
        ],
        highlightKey: 26,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getBasicPay')-Microtask"],
        webApis: [],
        callStack: ["fetch('getHra')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
        ],
        highlightKey: 27,
      },
      {
        taskQueue: [],
        microTaskQueue: ["fetch('getBasicPay')-Microtask"],
        webApis: [],
        callStack: [],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
        ],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["fetch('getBasicPay')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
        ],
        highlightKey: 14,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('getBasicPay request done')",
          "fetch('getBasicPay')-Microtask",
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
        ],
        highlightKey: 15,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['resolve(data)', "fetch('getBasicPay')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
        ],
        highlightKey: 16,
      },
      {
        taskQueue: [],
        microTaskQueue: ['Salary Data-Microtask'],
        webApis: [],
        callStack: ["fetch('getBasicPay')-Microtask"],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
        ],
        highlightKey: 17,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['Salary Data-Microtask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
        ],
        highlightKey: 35,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          "console.log('Salary Done', result)",
          'Salary Data-Microtask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
        ],
        highlightKey: 36,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [
          'salary = result[0] + result[1]',
          'Salary Data-Microtask',
        ],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
          'Salary Done',
        ],
        highlightKey: 37,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['Salary Data-Microtask'],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
          'Salary Done',
        ],
        highlightKey: 38,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [],
        log: [
          'getEmpDetails Start',
          'getEmpDetails EOF',
          'EOF',
          'getEmpDetails request done',
          'getEmpDetails Done',
          'getHra Start',
          'getHra EOF',
          'getBasicPay Start',
          'getBasicPay EOF',
          'getHra request done',
          'getBasicPay request done',
          'Salary Done',
        ],
        highlightKey: 0,
      },
    ],
  },
  'async-await-exec': {
    imageSrc: '../../assets/code-snippets/async-await-exec.png',
    code: `
async function getEmpDetails(emp) {
  console.log('getEmpDetails Start');
  const empDetails = await fetch('https://myorg.com/api/getEmpDetails/' + emp);
  console.log('getEmpDetails request done');
  console.log('getEmpDetails EOF');
  return empDetails;
}
async function getBasicPay(emp) {
  console.log('getBasicPay Start');
  const basicPay = await fetch('https://myorg.com/api/getBasicPay/' + emp);
  console.log('getBasicPay request done');
  console.log('getBasicPay EOF');
  return getBasicPay;
}
async function getHra(emp) {
  console.log('getHra Start');
  const basicPay = await fetch('https://myorg.com/api/getHra/' + emp);
  console.log('getHra request done');
  console.log('getHra EOF');
  return basicPay;
}
async function calcSalary() {
  const empDetails = await getEmpDetails('emp');
  console.log('getEmpDetails Done', empDetails);
  const [hra, bascicPay] = await Promise.all([getHra(details), getBasicPay(details)]);
  console.log('Salary Done', {hra, bascicPay});
  return hra + bascicPay;
}
calcSalary().then(totalSalary => console.log('Total Salary', totalSalary));
console.log('EOF');
`,
    codeLines: [
      '1. async function getEmpDetails(emp) {',
      "2.   console.log('getEmpDetails Start');",
      "3.   const empDetails = await fetch('https://myorg.com/api/getEmpDetails/' + emp);",
      "4.   console.log('getEmpDetails request done');",
      "5.   console.log('getEmpDetails EOF');",
      '6.   return empDetails;',
      '7. }',
      '8. async function getBasicPay(emp) {',
      "9.    console.log('getBasicPay Start');",
      "10.   const basicPay = await fetch('https://myorg.com/api/getBasicPay/' + emp);",
      "11.   console.log('getBasicPay request done');",
      "12.   console.log('getBasicPay EOF');",
      '13.   return getBasicPay;',
      '14. }',
      '15. async function getHra(emp) {',
      "16.   console.log('getHra Start');",
      "17.   const basicPay = await fetch('https://myorg.com/api/getHra/' + emp);",
      "18.   console.log('getHra request done');",
      "19.   console.log('getHra EOF');",
      '20.   return basicPay;',
      '21. }',
      '22. async function calcSalary() {',
      "23.   const empDetails = await getEmpDetails('emp');",
      "24.   console.log('getEmpDetails Done', empDetails);",
      '25.   const [hra, bascicPay] = await Promise.all([getHra(empDetails), getBasicPay(empDetails)]);',
      "26.   console.log('Salary Done', {hra, bascicPay});",
      '27.   return hra + bascicPay;',
      '28. }',
      "29. calcSalary().then(totalSalary => console.log('Total Salary', totalSalary));",
      "30. console.log('EOF');",
    ],
    examples: [
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [],
        log: [],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['calcSalary()'],
        log: [],
        highlightKey: 29,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['getEmpDetails(emp)', 'calcSalary()'],
        log: [],
        highlightKey: 23,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getEmpDetails Start')", 'getEmpDetails(emp)', 'calcSalary()'],
        log: [],
        highlightKey: 2,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["fetch('getEmpDetails')", 'getEmpDetails(emp)', 'calcSalary()'],
        log: ['getEmpDetails Start'],
        highlightKey: 3,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getEmpDetails')-Pending", ],
        callStack: ['getEmpDetails(emp)', 'calcSalary()'],
        log: ['getEmpDetails Start'],
        highlightKey: 7,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getEmpDetails')-Resolved", ],
        callStack: ['calcSalary()'],
        log: ['getEmpDetails Start'],
        highlightKey: 28,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getEmpDetails-Resume-Microtask", ],
        webApis: [],
        callStack: ["console.log('EOF')"],
        log: ['getEmpDetails Start'],
        highlightKey: 30,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getEmpDetails-Resume-Microtask", ],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["getEmpDetails-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF'],
        highlightKey: 3,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getEmpDetails request done')" ,"getEmpDetails-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF'],
        highlightKey: 4,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getEmpDetails EOF')" ,"getEmpDetails-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done'],
        highlightKey: 5,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["return empDetails" ,"getEmpDetails-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF'],
        highlightKey: 6,
      },
      {
        taskQueue: [],
        microTaskQueue: ["calcSalary-Resume-Microtask"],
        webApis: [],
        callStack: ["getEmpDetails-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF'],
        highlightKey: 7,
      },
      {
        taskQueue: [],
        microTaskQueue: ["calcSalary-Resume-Microtask"],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF'],
        highlightKey: 23,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getEmpDetails Done', empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF'],
        highlightKey: 24,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["getHra(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done'],
        highlightKey: 25,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getHra Start')", "getHra(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done'],
        highlightKey: 16,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["fetch('getHra')", "getHra(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start'],
        highlightKey: 17,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getHra')-Pending", ],
        callStack: ["getHra(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start'],
        highlightKey: 21,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: ["fetch('getHra')-Resolved", ],
        callStack: ["getBasicPay(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start'],
        highlightKey: 25,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask"],
        webApis: [],
        callStack: ["getBasicPay(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start'],
        highlightKey: 25,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask"],
        webApis: [],
        callStack: ["console.log('getBasicPay Start')", "getBasicPay(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start'],
        highlightKey: 9,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask"],
        webApis: [],
        callStack: ["fetch('getBasicPay')", "getBasicPay(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 10,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask"],
        webApis: ["fetch('getBasicPay')-Pending"],
        callStack: ["getBasicPay(empDetails)", "calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 14,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask"],
        webApis: ["fetch('getBasicPay')-Resolved"],
        callStack: ["calcSalary-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 28,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getHra-Resume-Microtask", "getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: ["getHra-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 17,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: ["console.log('getHra request done')", "getHra-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start'],
        highlightKey: 18,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: ["console.log('getHra EOF')", "getHra-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done'],
        highlightKey: 19,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: ["return basicPay", "getHra-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF'],
        highlightKey: 20,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: ["getHra-Resume-Microtask", ],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF'],
        highlightKey: 21,
      },
      {
        taskQueue: [],
        microTaskQueue: ["getBasicPay-Resume-Microtask"],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["getBasicPay-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF'],
        highlightKey: 10,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getBasicPay request done')", "getBasicPay-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF'],
        highlightKey: 11,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('getBasicPay EOF')", "getBasicPay-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done'],
        highlightKey: 12,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["return getBasicPay", "getBasicPay-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF'],
        highlightKey: 13,
      },
      {
        taskQueue: [],
        microTaskQueue: ['calcSalary-Resume-Microtask'],
        webApis: [],
        callStack: ["getBasicPay-Resume-Microtask"],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF'],
        highlightKey: 14,
      },
      {
        taskQueue: [],
        microTaskQueue: ['calcSalary-Resume-Microtask'],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['calcSalary-Resume-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF'],
        highlightKey: 25,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('Salary Done', {hra, bascicPay})", 'calcSalary-Resume-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF'],
        highlightKey: 26,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["return hra + basicPay", 'calcSalary-Resume-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done'],
        highlightKey: 27,
      },
      {
        taskQueue: [],
        microTaskQueue: ['totalSalary-Microtask'],
        webApis: [],
        callStack: ['calcSalary-Resume-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done'],
        highlightKey: 28,
      },
      {
        taskQueue: [],
        microTaskQueue: ['totalSalary-Microtask'],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done'],
        highlightKey: 0,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['totalSalary-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done'],
        highlightKey: 29,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ["console.log('Total Salary', totalSalary)", 'totalSalary-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done'],
        highlightKey: 29,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: ['totalSalary-Microtask'],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done', 'Total Salary'],
        highlightKey: 29,
      },
      {
        taskQueue: [],
        microTaskQueue: [],
        webApis: [],
        callStack: [],
        log: ['getEmpDetails Start', 'EOF', 'getEmpDetails request done', 'getEmpDetails EOF', 'getEmpDetails Done', 'getHra Start', 'getBasicPay Start', 'getHra request done', 'getHra EOF', 'getBasicPay request done', 'getBasicPay EOF', 'Salary Done', 'Total Salary'],
        highlightKey: 0,
      },
    ],
  },
};
